### ISSUE TITLE
Photo can't be shown completely

### ISSUE THREAD

**Issue by bobmulder** [Odonno/Modern-Gitter#14]
Hi,

I know images are supported in the chat. However, I can't read it (because it's mostly code :P), so I usually press the image to see it full screen and zoom in and stuff, but it's not possible.

Are you able to add this feature?

Greetz

**Comment by Odonno** [comment]
Hi @bobmulder,

It is coming in the next version 1.2.2.
Once you have tested it, could you send me a message if it is working as expected ?

**Comment by bobmulder** [comment]
Should i test before release?

**Comment by Odonno** [comment]
The new version is already pushed on the Store. Just wait.

**Comment by bobmulder** [comment]
I think you should look for a windows-phone way. I can't believe there is no default way to do this... Take a look at https://msdn.microsoft.com/en-us/library/windows/apps/hh202966(v=vs.105).aspx maybe?

**Comment by Odonno** [comment]
Your link references a documentation for WP8 Silverlight. I am on WinRT (8.1) and it does not work the same way.

I use this Stackoverflow http://stackoverflow.com/questions/13782810/using-scrollviewer-for-image-pinch-zoom-keeps-snapping-left-on-pan and it works pretty well. If you need more features on full image (save, share, etc...) I think I'll have to do on my own.

**Comment by Odonno** [comment]
It is now perfectly showed on the new version except images are in bad quality #21

**Comment by bobmulder** [comment]
:+1:
