### ISSUE TITLE
Toast notifications on mention

### ISSUE THREAD

**Issue by Odonno** [Odonno/Modern-Gitter#17]
When someone mention you on a chat room (*@/all* or *@/username*), the user should receive a Toast Notification.

**Comment by Odonno** [comment]
To finish the feature, I need to retrieve mentioned messages via their id. https://github.com/gitterHQ/gitter/issues/890

**Comment by SuperJMN** [comment]
In addition to this, I suggest that there would be some indication of mentions and a way to "go to" those mentions, like in the web version of Gitter.

**Comment by Odonno** [comment]
Hum...

What I am doing now (not completed) is showing a toast notifications like `Odonno mentioned you (Modern-Gitter)`. When tapping the notification, you launch the app and navigate to the dedicated room.

What do you think ?

**Comment by gep13** [comment]
>In addition to this, I suggest that there would be some indication of mentions and a way to "go to" those mentions, like in the web version of Gitter.

Are you referring to the orange up or down arrow that appears on the right hand side of the chat room?

**Comment by Odonno** [comment]
@SuperJMN Can you answer ? I think in-app notification of mentions seems like a good idea. But, what did have in mind ?
