### ISSUE TITLE
Read formatted messages (HTML)

### ISSUE THREAD

**Issue by Odonno** [Odonno/Modern-Gitter#3]
Add availability to read HTML messages.

Parse HTML to show in message UI :
* [x] common HTML tags (title, bold, italic)
* [x] image
* [x] link (with redirection)
* [x] issue (with redirection)
* [x] mentions
* [x] blockquote
* [x] code (simple black/white)
* [x] formatted code
* [x] item list

**Comment by jaredallard** [comment]
:+1:

Sending markdown is just sent raw, I think. It's the parsing that needs to be done :)

**Comment by wassim-azirar** [comment]
Use MarkdownSharp

**Comment by Odonno** [comment]
@jaredallard I suppose you wish a Markdown editor ?

**Comment by jaredallard** [comment]
@Odonno No, just the ability to see markdown messages like, **bold**, instead of \*\*bold\*\*

**Comment by Odonno** [comment]
@jaredallard Yep, I see. But what about to write message in Markdown.

As I know, I can't read in Markdown because messages returned are converted in HTML in Gitter API. But, of course, I can read HTML in the app. https://developer.gitter.im/docs/messages-resource

**Comment by Odonno** [comment]
I'll take a look at https://winrthtml2xaml.codeplex.com/

**Comment by Odonno** [comment]
Ok, I implemented WinRT2XAML but the app crashed when it sees img...
I'll try other implementations like this one http://blogs.msdn.com/b/tess/archive/2013/05/13/displaying-html-content-in-a-richtextblock.aspx

**Comment by Odonno** [comment]
Yes, that implementation looks great with some custom code. In the next version, you will see images and links now !

![wp_ss_20150628_0001](https://cloud.githubusercontent.com/assets/6053067/8397670/ccef372a-1dd3-11e5-85b4-507014b2475f.png)
