### ISSUE TITLE
Problem with "Rate the app"

### ISSUE THREAD

**Issue by gep13** [Odonno/Modern-Gitter#31]
From time to time, I get the following pop up:

![wp_ss_20151026_0002](https://cloud.githubusercontent.com/assets/1271146/10740212/dfccdf02-7c18-11e5-9fe0-1ed978c78601.jpg)

However, everytime I click the yes button, I get taken through to the XBox Music, rather than to the store to actually rate the application.

**Comment by Odonno** [comment]
You're right !

Don't know from where it comes. I let you check this implementation : https://github.com/Odonno/Modern-Gitter/blob/master/Gitter/Gitter/Gitter.Shared/Services/Concrete/RatingService.cs. I've never seen that before...

Maybe a temporary bug ? Maybe...
