### ISSUE TITLE
Incorrect URL Navigation

### ISSUE THREAD

**Issue by gep13** [Odonno/Modern-Gitter#44]
In a recent chat in one of my rooms, I saw this link:

![wp_ss_20151101_0001](https://cloud.githubusercontent.com/assets/1271146/10869168/5120e994-809e-11e5-8af2-df46fcea57cf.jpg)

which is meant to take me to here:

https://github.com/github/linguist#2707

However, it actually, goes to this URL:

https://github.com/cake-build/cake/issues/2707

Which actually doesn't exist.  It is almost like it it concatenating the 2707 onto the URL for the Room on GitHub, rather than the URL that is being shown.

Any thoughts on what is going on here?

**Comment by Odonno** [comment]
We'll check that deeper. Don't know where it comes from at this time.

**Comment by Odonno** [comment]
You can fix bug by looking at method `GenerateIssueLink` in file https://github.com/Odonno/Modern-Gitter/blob/master/Gitter/Gitter.HtmlToXaml/Helpers/NodeHelper.cs, line 216

**Comment by Odonno** [comment]
That should do it !

**Comment by Odonno** [comment]
@gep13 I have done the same for Pull Request, but I found a bug about HTML sent by API. See https://github.com/gitterHQ/gitter/issues/974

**Comment by Odonno** [comment]
@gep13 Does it works now ?

**Comment by gep13** [comment]
Yes, I believe that this is now working! :+1:
