### ISSUE TITLE
Add contribute section to readme

### ISSUE THREAD

**Issue by Odonno** [Odonno/Modern-Gitter#47]
Add a Contribute section that explains how to contribute effectively : 

* [x] list of contributors
* [x] git commit convention

Followed by @NPadrutt

**Comment by Odonno** [comment]
@gep13 @npadrutt What do you think about that ? (check readme)

**Comment by gep13** [comment]
I think it is a good start.  For me, starting out with it, I wasn't clear on what the conventions were, and how they would apply to this project.   So what I think might help would be some examples.  For example, what would be the suggested commit message:

* when fixing a bug with the Notifications
* when adding a new feature related to Notifications
* when fixing an issue with the build
* when adding some documentation

Granted, the user might be able to find those things by clicking on that link that you provide, and digging through the documentation there, but I also think a few quick examples on your readme would help the people that you want to contribute here.

Also, I am not sure what you mean here:

`I apologies contributors to help me on this project.`

I think `apologies` is the wrong word, but not clear on what you were going for here.

**Comment by gep13** [comment]
Also, shouldn't CorentinMiq be in the list?

**Comment by NPadrutt** [comment]
I aggree on what @gep13 wrote. I think contributing should be as easy as possible, therefore the relevant parts should be directly accessible without following a link.

I update my PR with the convention. Maybe I see something noteworthy =)

**Comment by Odonno** [comment]
> Also, shouldn't CorentinMiq be in the list?

Of course, I'll add it.

**Comment by Odonno** [comment]
@gep13 @npadrutt I'll make some examples about commit convention.

**Comment by Odonno** [comment]
@gep13 Thanks for the examples.

What do you think about it, now ?

**Comment by gep13** [comment]
@Odonno said...
What do you think about it, now ?

This looks much better to me.  Just a couple small things...

`Here is some` should be `Here are some`

`I thank contributors to help me on this project.` should be `I want to thank the following contributors who have helped me this project`

**Comment by Odonno** [comment]
Thank you. I think it's done.
