### ISSUE TITLE
Add german translation

### ISSUE THREAD

**Issue by NPadrutt** [Odonno/Modern-Gitter#48]

**Comment by Odonno** [comment]
To finally publish the update, could ou translate these sentences ?

```
This is a non official client app for Gitter.

The app contains features like :

* current list of rooms
* chat messages in realtime (send / receive)
* realtime in-app notifications
* delayed notifications when app is not running
```

And those keywords : 

```
Social
Collaborative
Chat
```

Thanks.

**Comment by NPadrutt** [comment]
here you go:

Das ist ein inoffizieller Client für Gitter.

Folgende Funktionen sind enthalten:
- Liste der aktuellen Räume
- Chat Nachrichten in Echtzeit (Senden / Empfangen)
- Echtzeit In-App Benachrichtigung
- Verzögerte Benachrichtigung wenn das App nicht läuft

Keywords:
- Sozial
- Zusammenarbeit
- Chat

**Comment by Odonno** [comment]
Gut !

**Comment by Odonno** [comment]
@NPadrutt It's done. Can you confirm ?

**Comment by NPadrutt** [comment]
yeah!
