### ISSUE TITLE
Improve chat list

### ISSUE THREAD

**Issue by Odonno** [Odonno/Modern-Gitter#9]
Improve the way user see the chat list (as same as on gitter), ordered by some properties.

* [x] by favourites first
* [x] by unread mentions second
* [x] by unread items then
* [x] finally ordered by last accessed time

**Comment by bobmulder** [comment]
:+1:

**Comment by Odonno** [comment]
The order works fine now, the same as in the official web version.
Coming in a future version...

**Comment by bobmulder** [comment]
:+1:
